name: Publish SDK to NPM

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.0)'
        required: true
        type: string
        default: '0.0.41'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Show current version
        run: |
          CURRENT_VERSION=$(cat packages/sdk/package.json | grep '"version"' | sed 's/.*"version": "\(.*\)".*/\1/')
          echo "::notice title=Current Version::Current SDK version is $CURRENT_VERSION"
          echo "::notice title=New Version::Will update to version ${{ inputs.version }}"

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Update package version
        run: |
          npm version ${{ inputs.version }} --no-git-tag-version --allow-same-version --prefix packages/sdk

      - name: Create version update branch and PR
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          
          # Create and switch to a new branch
          BRANCH_NAME="update-sdk-version-${{ inputs.version }}"
          git checkout -b $BRANCH_NAME
          
          # Stage and commit the changes
          git add packages/sdk/package.json
          git commit -s -m "Update SDK version to ${{ inputs.version }}"
          
          # Push the branch
          git push origin $BRANCH_NAME
          
          # Create a pull request using GitHub CLI
          gh pr create \
            --title "Update SDK version to ${{ inputs.version }}" \
            --body "Automated version update from ${{ inputs.version }} release workflow." \
            --head $BRANCH_NAME \
            --base main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build package
        run: |
          cd packages/sdk
          NODE_ENV=production bun run build

      - name: Publish to NPM
        run: |
          cd packages/sdk
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
